name: servant-serf
version: 0.1.1
category: Code Generation
synopsis: Generates a servant API module
description: A preprocessor which will parse a psuedo-haskell module with imports and generate a module with exports a Route type and a server function
maintainer: ACI Learning
github: EdutainmentLIVE/servant-serf
license: MIT
extra-source-files: README.md

library:
  when:
    - condition: false
      other-modules: Paths_servant_serf

executable:
  source-dirs: app
  main: Main.hs
  when:
    - condition: false
      other-modules: Paths_servant_serf
  dependencies:
    - attoparsec
    - base <= 5.2.0.0
    - hpack
    - mtl
    - optparse-applicative
    - regex-base
    - regex-tdfa >= 1.3.1.0
    - text

ghc-options:
  - -Weverything
  - -Wno-all-missed-specializations
  - -Wno-implicit-prelude
  - -Wno-missed-specialisations
  - -Wno-missing-deriving-strategies
  - -Wno-missing-export-lists
  - -Wno-missing-exported-signatures
  - -Wno-missing-import-lists
  - -Wno-redundant-constraints
  - -Wno-safe
  - -Wno-unsafe
