name: servant-serf
version: 0.0.1

library:
  when:
    - condition: false
      other-modules: Paths_servant_serf
 

executable:
  source-dirs: app
  main: Main.hs
  when:
    - condition: false
      other-modules: Paths_servant_serf
  dependencies:
    - attoparsec
    - base
    - hpack
    - mtl
    - optparse-applicative
    - parser-combinators
    - regex-base
    - regex-tdfa >= 1.3.1.0
    - text
    - tomland

ghc-options:
  - -Weverything
  - -Wno-all-missed-specializations
  - -Wno-implicit-prelude
  - -Wno-missed-specialisations
  - -Wno-missing-deriving-strategies
  - -Wno-missing-export-lists
  - -Wno-missing-exported-signatures
  - -Wno-missing-import-lists
  - -Wno-redundant-constraints
  - -Wno-safe
  - -Wno-unsafe
  - -Werror
